# Generated by Django 4.2.13 on 2024-12-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_facility_location_alter_facility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='facility',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.facility'),
        ),
    ]
