# Generated by Django 4.2.13 on 2024-12-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_appointmentschedule_doctor'),
        ('patient', '0002_appointment_billing_healtheducationresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_record', to='patient.appointment'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patient.patient'),
        ),
    ]
