# Generated by Django 4.2.13 on 2024-12-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_appointmentschedule_doctor'),
        ('patient', '0004_remove_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healtheducationresource',
            name='file',
        ),
        migrations.AddField(
            model_name='healtheducationresource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='patient.appointment'),
            preserve_default=False,
        ),
    ]
