# Generated by Django 4.2.13 on 2024-12-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctor.doctor'),
        ),
    ]
